name: Tara Vanhatalo
email: tara.vanhatalo@u-bordeaux.fr
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-include-cache
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
