name: Tara Vanhatalo
email: tara.vanhatalo@gmail.com
markdown: kramdown
# permalink: /:categories/:title/
title: "Tara Vanhatalo"
url: "tvanhatalo.github.io"
header:
  image: /assets/img/ShaderTest_1.png

include:
  - _pages

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

author:
  name   : "Tara Vanhatalo"
  avatar : "/assets/img/bio-photo.png"
  bio    : "Co-founder @ Allendia."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tvanhatalo"
    - label: "Allendia"
      icon: "fas fa-fw fa-compact-disc"
      url: "https://allendia.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tara-vanhatalo-22a44b16a/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

